// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package binary

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadGetTpIp returns the embedded CollectionSpec for GetTpIp.
func LoadGetTpIp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GetTpIpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load GetTpIp: %w", err)
	}

	return spec, err
}

// LoadGetTpIpObjects loads GetTpIp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*GetTpIpObjects
//	*GetTpIpPrograms
//	*GetTpIpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadGetTpIpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadGetTpIp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// GetTpIpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GetTpIpSpecs struct {
	GetTpIpProgramSpecs
	GetTpIpMapSpecs
	GetTpIpVariableSpecs
}

// GetTpIpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GetTpIpProgramSpecs struct {
	TraceOpenStack *ebpf.ProgramSpec `ebpf:"trace_open_stack"`
}

// GetTpIpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GetTpIpMapSpecs struct {
	StackTraces *ebpf.MapSpec `ebpf:"stack_traces"`
}

// GetTpIpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GetTpIpVariableSpecs struct {
}

// GetTpIpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadGetTpIpObjects or ebpf.CollectionSpec.LoadAndAssign.
type GetTpIpObjects struct {
	GetTpIpPrograms
	GetTpIpMaps
	GetTpIpVariables
}

func (o *GetTpIpObjects) Close() error {
	return _GetTpIpClose(
		&o.GetTpIpPrograms,
		&o.GetTpIpMaps,
	)
}

// GetTpIpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadGetTpIpObjects or ebpf.CollectionSpec.LoadAndAssign.
type GetTpIpMaps struct {
	StackTraces *ebpf.Map `ebpf:"stack_traces"`
}

func (m *GetTpIpMaps) Close() error {
	return _GetTpIpClose(
		m.StackTraces,
	)
}

// GetTpIpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadGetTpIpObjects or ebpf.CollectionSpec.LoadAndAssign.
type GetTpIpVariables struct {
}

// GetTpIpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadGetTpIpObjects or ebpf.CollectionSpec.LoadAndAssign.
type GetTpIpPrograms struct {
	TraceOpenStack *ebpf.Program `ebpf:"trace_open_stack"`
}

func (p *GetTpIpPrograms) Close() error {
	return _GetTpIpClose(
		p.TraceOpenStack,
	)
}

func _GetTpIpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gettpip_x86_bpfel.o
var _GetTpIpBytes []byte
