// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package binary

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type MemleakAllocInfo struct {
	Size        uint64
	TimestampNs uint64
	StackId     int32
	_           [4]byte
}

type MemleakCombinedAllocInfo struct{ T struct{ _ [8]byte } }

// LoadMemleak returns the embedded CollectionSpec for Memleak.
func LoadMemleak() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MemleakBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Memleak: %w", err)
	}

	return spec, err
}

// LoadMemleakObjects loads Memleak and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MemleakObjects
//	*MemleakPrograms
//	*MemleakMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMemleakObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMemleak()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MemleakSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemleakSpecs struct {
	MemleakProgramSpecs
	MemleakMapSpecs
	MemleakVariableSpecs
}

// MemleakProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemleakProgramSpecs struct {
	FreeEnter   *ebpf.ProgramSpec `ebpf:"free_enter"`
	MallocEnter *ebpf.ProgramSpec `ebpf:"malloc_enter"`
	MallocExit  *ebpf.ProgramSpec `ebpf:"malloc_exit"`
}

// MemleakMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemleakMapSpecs struct {
	Allocs         *ebpf.MapSpec `ebpf:"allocs"`
	CombinedAllocs *ebpf.MapSpec `ebpf:"combined_allocs"`
	Memptrs        *ebpf.MapSpec `ebpf:"memptrs"`
	Sizes          *ebpf.MapSpec `ebpf:"sizes"`
	StackTraces    *ebpf.MapSpec `ebpf:"stack_traces"`
}

// MemleakVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemleakVariableSpecs struct {
	MaxSize    *ebpf.VariableSpec `ebpf:"max_size"`
	MinSize    *ebpf.VariableSpec `ebpf:"min_size"`
	StackFlags *ebpf.VariableSpec `ebpf:"stack_flags"`
}

// MemleakObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMemleakObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemleakObjects struct {
	MemleakPrograms
	MemleakMaps
	MemleakVariables
}

func (o *MemleakObjects) Close() error {
	return _MemleakClose(
		&o.MemleakPrograms,
		&o.MemleakMaps,
	)
}

// MemleakMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMemleakObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemleakMaps struct {
	Allocs         *ebpf.Map `ebpf:"allocs"`
	CombinedAllocs *ebpf.Map `ebpf:"combined_allocs"`
	Memptrs        *ebpf.Map `ebpf:"memptrs"`
	Sizes          *ebpf.Map `ebpf:"sizes"`
	StackTraces    *ebpf.Map `ebpf:"stack_traces"`
}

func (m *MemleakMaps) Close() error {
	return _MemleakClose(
		m.Allocs,
		m.CombinedAllocs,
		m.Memptrs,
		m.Sizes,
		m.StackTraces,
	)
}

// MemleakVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMemleakObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemleakVariables struct {
	MaxSize    *ebpf.Variable `ebpf:"max_size"`
	MinSize    *ebpf.Variable `ebpf:"min_size"`
	StackFlags *ebpf.Variable `ebpf:"stack_flags"`
}

// MemleakPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMemleakObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemleakPrograms struct {
	FreeEnter   *ebpf.Program `ebpf:"free_enter"`
	MallocEnter *ebpf.Program `ebpf:"malloc_enter"`
	MallocExit  *ebpf.Program `ebpf:"malloc_exit"`
}

func (p *MemleakPrograms) Close() error {
	return _MemleakClose(
		p.FreeEnter,
		p.MallocEnter,
		p.MallocExit,
	)
}

func _MemleakClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed memleak_arm64_bpfel.o
var _MemleakBytes []byte
