// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package binary

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type soft_lockWatchdogTrackingInfo struct {
	LastTimestamp   uint64
	TouchCount      uint32
	SoftLockupCount uint32
	HardLockupCount uint32
}

// loadSoft_lock returns the embedded CollectionSpec for soft_lock.
func loadSoft_lock() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Soft_lockBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load soft_lock: %w", err)
	}

	return spec, err
}

// loadSoft_lockObjects loads soft_lock and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*soft_lockObjects
//	*soft_lockPrograms
//	*soft_lockMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSoft_lockObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSoft_lock()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// soft_lockSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type soft_lockSpecs struct {
	soft_lockProgramSpecs
	soft_lockMapSpecs
	soft_lockVariableSpecs
}

// soft_lockProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type soft_lockProgramSpecs struct {
	TraceWatchdogTimer *ebpf.ProgramSpec `ebpf:"trace_watchdog_timer"`
}

// soft_lockMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type soft_lockMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	WatchdogMap *ebpf.MapSpec `ebpf:"watchdog_map"`
}

// soft_lockVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type soft_lockVariableSpecs struct {
	UnusedSoftLockupEvent      *ebpf.VariableSpec `ebpf:"unused_soft_lockup_event"`
	UnusedWatchdogTrackingInfo *ebpf.VariableSpec `ebpf:"unused_watchdog_tracking_info"`
}

// soft_lockObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSoft_lockObjects or ebpf.CollectionSpec.LoadAndAssign.
type soft_lockObjects struct {
	soft_lockPrograms
	soft_lockMaps
	soft_lockVariables
}

func (o *soft_lockObjects) Close() error {
	return _Soft_lockClose(
		&o.soft_lockPrograms,
		&o.soft_lockMaps,
	)
}

// soft_lockMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSoft_lockObjects or ebpf.CollectionSpec.LoadAndAssign.
type soft_lockMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	WatchdogMap *ebpf.Map `ebpf:"watchdog_map"`
}

func (m *soft_lockMaps) Close() error {
	return _Soft_lockClose(
		m.Events,
		m.WatchdogMap,
	)
}

// soft_lockVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSoft_lockObjects or ebpf.CollectionSpec.LoadAndAssign.
type soft_lockVariables struct {
	UnusedSoftLockupEvent      *ebpf.Variable `ebpf:"unused_soft_lockup_event"`
	UnusedWatchdogTrackingInfo *ebpf.Variable `ebpf:"unused_watchdog_tracking_info"`
}

// soft_lockPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSoft_lockObjects or ebpf.CollectionSpec.LoadAndAssign.
type soft_lockPrograms struct {
	TraceWatchdogTimer *ebpf.Program `ebpf:"trace_watchdog_timer"`
}

func (p *soft_lockPrograms) Close() error {
	return _Soft_lockClose(
		p.TraceWatchdogTimer,
	)
}

func _Soft_lockClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed soft_lock_x86_bpfel.o
var _Soft_lockBytes []byte
