// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package binary

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type SoftLockSoftLockupEvent struct {
	Cpu       uint32
	Timestamp uint64
	Interval  uint64
	Pid       uint32
	Comm      [16]int8
}

type SoftLockWatchdogTrackingInfo struct {
	LastTimestamp   uint64
	TouchCount      uint32
	SoftLockupCount uint32
	HardLockupCount uint32
}

// LoadSoftLock returns the embedded CollectionSpec for SoftLock.
func LoadSoftLock() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SoftLockBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SoftLock: %w", err)
	}

	return spec, err
}

// LoadSoftLockObjects loads SoftLock and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SoftLockObjects
//	*SoftLockPrograms
//	*SoftLockMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSoftLockObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSoftLock()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SoftLockSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SoftLockSpecs struct {
	SoftLockProgramSpecs
	SoftLockMapSpecs
	SoftLockVariableSpecs
}

// SoftLockProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SoftLockProgramSpecs struct {
	TraceNativeQueuedSpinLockSlowpath *ebpf.ProgramSpec `ebpf:"trace_native_queued_spin_lock_slowpath"`
	TraceTaskDumpOwner                *ebpf.ProgramSpec `ebpf:"trace_task_dump_owner"`
	TraceWatchdogTimer                *ebpf.ProgramSpec `ebpf:"trace_watchdog_timer"`
}

// SoftLockMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SoftLockMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	WatchdogMap *ebpf.MapSpec `ebpf:"watchdog_map"`
}

// SoftLockVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SoftLockVariableSpecs struct {
	UnusedSoftLockupEvent      *ebpf.VariableSpec `ebpf:"unused_soft_lockup_event"`
	UnusedWatchdogTrackingInfo *ebpf.VariableSpec `ebpf:"unused_watchdog_tracking_info"`
}

// SoftLockObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSoftLockObjects or ebpf.CollectionSpec.LoadAndAssign.
type SoftLockObjects struct {
	SoftLockPrograms
	SoftLockMaps
	SoftLockVariables
}

func (o *SoftLockObjects) Close() error {
	return _SoftLockClose(
		&o.SoftLockPrograms,
		&o.SoftLockMaps,
	)
}

// SoftLockMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSoftLockObjects or ebpf.CollectionSpec.LoadAndAssign.
type SoftLockMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	WatchdogMap *ebpf.Map `ebpf:"watchdog_map"`
}

func (m *SoftLockMaps) Close() error {
	return _SoftLockClose(
		m.Events,
		m.WatchdogMap,
	)
}

// SoftLockVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSoftLockObjects or ebpf.CollectionSpec.LoadAndAssign.
type SoftLockVariables struct {
	UnusedSoftLockupEvent      *ebpf.Variable `ebpf:"unused_soft_lockup_event"`
	UnusedWatchdogTrackingInfo *ebpf.Variable `ebpf:"unused_watchdog_tracking_info"`
}

// SoftLockPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSoftLockObjects or ebpf.CollectionSpec.LoadAndAssign.
type SoftLockPrograms struct {
	TraceNativeQueuedSpinLockSlowpath *ebpf.Program `ebpf:"trace_native_queued_spin_lock_slowpath"`
	TraceTaskDumpOwner                *ebpf.Program `ebpf:"trace_task_dump_owner"`
	TraceWatchdogTimer                *ebpf.Program `ebpf:"trace_watchdog_timer"`
}

func (p *SoftLockPrograms) Close() error {
	return _SoftLockClose(
		p.TraceNativeQueuedSpinLockSlowpath,
		p.TraceTaskDumpOwner,
		p.TraceWatchdogTimer,
	)
}

func _SoftLockClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed softlock_arm64_bpfel.o
var _SoftLockBytes []byte
